### ISSUE TITLE
Incohérence sur les valeurs configurées sur mon cluster et celle qui s'affiche sur le dashboard

### ISSUE THREAD

**Issue by abzogodwin** [FairwindsOps/goldilocks#163]
Bonjour 

on my cluster for the resource requests / limits of my component I configured as follows:
`        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 300m

`
and here is what I observe in the goldilocks dashboard:

  | Current |   | Guaranteed
-- | -- | -- | --
CPU Request | 200m |   | 25m
CPU Limit | 1000m |   | 25m
Mem Request | 1024Mi |   | 250Mi
Mem Limit | 1024Mi |   | 250Mi

I do not understand why this difference in current?

**Comment by sudermanjr** [comment]
That's interesting. We will have to take a look and see if perhaps there is a bug.

**Comment by lucasreed** [comment]
I have not confirmed this, but my first instinct is that you are seeing this issue because you specified a lowercase `m` in your memory request, which is in fact not valid for a memory resource setting (It should be either `M` or `Mi`) but the api-server will accept it. According to [this issue](https://github.com/kubernetes/kubernetes/issues/79950) it could be more dangerous than it seems assuming you are running linux.
