### ISSUE TITLE
Prefix VPAs

### ISSUE THREAD

**Issue by estahn** [FairwindsOps/goldilocks#205]
VPAs should be prefixed with a configurable prefix (e.g. `goldilocks-`) to avoid collisions with existing VPAs.

**Comment by lgmorand** [comment]
+1

**Comment by sudermanjr** [comment]
Agreed, this is definitely a worth feature. Anyone reading this should also see my comment on #206. The current way we do the `summary` is going to be largely incompatible with both this and being able to show all VPA objects. 

In general, a rewrite of how we handle ownership is called for here.

**Comment by estahn** [comment]
@lgmorand Just revisiting goldilocks and was wondering if PRs are accepted?

**Comment by lgmorand** [comment]
of course. I'm not the owner but as you can see, there are 225PRs already accepted

**Comment by HariSekhon** [comment]
This is very worth doing - I don't want to have to remove existing VPAs just so that Goldilocks can use the name.

It would probably have been a good idea for the VPAs to be prefixed or suffixed with "goldilocks" anyway, as otherwise they could get overwritten by other Kubernetes CI/CD systems even if goldilocks put them there first.
