### ISSUE TITLE
Display existing VPAs on Dashboard

### ISSUE THREAD

**Issue by estahn** [FairwindsOps/goldilocks#206]
Is there a particular reason Goldilocks only displays VPAs it created? If not, then it should display all existing VPAs.

**Comment by lgmorand** [comment]
not sure. if these VPAs aren't used by goldilocks to display info, (or duplicate info with created VPAs), what would be the value ?

**Comment by estahn** [comment]
It would be great as a generic UI/Dashboard for VPAs.

**Comment by sudermanjr** [comment]
I took a look at this and started working on it. I think this will require or go nicely with #205. 

Currently, we assume that vpa.Name == deployment.Name in order to aggregate the VPA recommendations with the current requests/limits on the containers in the deployment. This means that if we decide to show all VPAs without changing up the logic linking VPAs to Deployments, we will not be able to show them correctly.

If this is something we decide to pursue, it will be a rather large rewrite of the underlying logic. We would need to start creating the VPAs with the selectors, and then in the summarizer start following that link back, instead of assuming the names are equal. We can do this, but it will not be trivial and should be undertaken with care.

**Comment by sudermanjr** [comment]
A couple more notes/questions on this:

1) I think this should be a flag on the dashboard and be disabled by default
2) Does this mean that enabling the flag would show all of the VPAs in the cluster, regardless of Goldilocks labelling? Or would we still respect the labelling of the namespace?

**Comment by HariSekhon** [comment]
I hadalready had created a lot of VPAs ages back for my production systems to monitor them in the CLI.

Not only does Goldilocks not show the existing VPAs but it doesn't create alternative ones to be used in Goldilocks for the existing deployments and statefulsets, possibly due to name clash?

**Comment by sudermanjr** [comment]
@HariSekhon This has actually changed recently, we added a prefix to all VPA names so that they do not collide

**Comment by HariSekhon** [comment]
@sudermanjr Yes I saw this thanks, I did a helm chart image override to upgrade to v4.1.0 about 3 weeks back to make use of this ahead of a new helm chart release becoming available so that I could make use of it and work around conflicts with existing VPAs for live apps.

**Comment by dennislapchenko** [comment]
@sudermanjr Hey! Any updates when viewing existing VPAs would be available?
You mention now that you add a prefix, so its not `vpa.Name == deployment.Name` anymore?

Would be nice to utilize existing VPAs for this, rather than wipe them and then recreate via goldilocks and wait for it to learn useful data.
Have to say generating VPAs for all workloads is easier than having VPAs in each chart (common chart in my case), however would still be nice to view anything thats already there.

Possibly a yet better solution would be to map existing VPAs to what goldilocks expects to create in a given namespace. this would sort of "import" the VPA. would give a nice headstart to those, who have VPAs before stumbling upon goldilocks.

Thanks

**Comment by HariSekhon** [comment]
+1 to using existing VPAs if found, saves creating lots of extra unnecessary VPAs when they already exist.

**Comment by sudermanjr** [comment]
@dennislapchenko and @HariSekhon 

"adopting" existing VPAs is a _very_ different ask than displaying existing VPAs on the dashboard. I would recommend opening a new issue for that request. 

RE: Showing existing on the dashboard, I have opened #433 to allow this. It will essentially display any VPA in the cluster, regardless of what created it. So you could in theory just run the goldilocks dashboard independent of the controller if you wanted.
