### ISSUE TITLE
multiple clusters functionality for the dashboard

### ISSUE THREAD

**Issue by claas-fridtjof-lisowski** [FairwindsOps/goldilocks#240]
We have multiple clusters and having the option to only have one dashboard were one can select the desired cluster would be helpful.
Otherwise I need x dashboards for each cluster a separate one.

Having the option to give a kube/.config file or a cluster registry endpoint, so that all clusters are accessed which are found, would be nice.

Are there any workarounds, how are other people solving this?

**Comment by rbren** [comment]
Thanks for reaching out! This is a fairly typical use case, but can be really difficult to implement in practice.

We've actually built a platform, [Fairwinds Insights](https://www.fairwinds.com/insights), which allows orgs to aggregate results from Goldilocks (as well as other k8s auditing tools like Trivy and Polaris) across all their clusters. It's a paid product rather than OSS (since we host a backend to do the aggregation), but you can start a free trial via the link above.

**Comment by claas-fridtjof-lisowski** [comment]
I will update this PR with the latest changes from the new release soon.
