### ISSUE TITLE
Dashboard showing empty

### ISSUE THREAD

**Issue by nitro2003** [FairwindsOps/goldilocks#292]
Hello, good day.

I am currently Goldilocks in our Dev cluster.
I followed the steps in the docs but it is showing empty in the dashboard.

![image](https://user-images.githubusercontent.com/10734493/108644990-23672c00-74ec-11eb-95cd-602d731202d1.png)

I can see the namespaces listed but when I try to expand each namespace, each deployment is empty.
I have metrics server installed and I am able to retrieve the CPU and memory usage.

![image](https://user-images.githubusercontent.com/10734493/108645113-adaf9000-74ec-11eb-9d26-a85063e722ce.png)

There is a bit of version discrepancy in the kubectl used. We just upgraded our Dev cluster to 1.18.

![image](https://user-images.githubusercontent.com/10734493/108645157-d768b700-74ec-11eb-85e9-4c0e2697d892.png)

Thanks!

**Comment by sudermanjr** [comment]
Are there VPA objects in the namespaces in question? If so, do they have recommendations available in their `status` ?

**Comment by nitro2003** [comment]
Thanks for your response @sudermanjr 
I do see the VPA objects in the namespaces but after checking it, the status field is empty.
![image](https://user-images.githubusercontent.com/10734493/108758287-e3ed1e00-7585-11eb-9872-dd9d485b6c0c.png)

**Comment by sudermanjr** [comment]
Usually that means either the metrics-server is not installed correctly (specifically the apiservice), or there's an issue in the recommender for VPA.

There's a couple things you can do to debug.

```
kubectl get apiservice  v1beta1.metrics.k8s.io
NAME                     SERVICE                         AVAILABLE   AGE
v1beta1.metrics.k8s.io   metrics-server/metrics-server   True        41s
```

That should show Available as True for that, pointing to your metrics-server installation.

The other thing is to check the logs on the recommender pod in your VPA installation.

**Comment by nitro2003** [comment]
Thank you for your help!
I was able to get this working.

For reference:
I was missing the VPA Recommender. 
I followed the instructions [here](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/README.md).

I assumed that the required VPA components would be installed with this being set:
`--set installVPA=true`
Maybe the documentation needs some clarifications?

Anyways, thanks for all your help!

**Comment by sudermanjr** [comment]
Glad you got it working! I think the value maybe have changed for that. Which instructions did you follow to install goldilocks?

**Comment by sudermanjr** [comment]
The latest helm installation instructions should be here: https://github.com/FairwindsOps/charts/tree/master/stable/vpa

**Comment by AvinashRamireddy31** [comment]
I have the same issue.

Instead of using helm chart I cloned from github and followed the instructions from https://goldilocks.docs.fairwinds.com/installation/#installation-2


I have both windows and linux node pools in my cluster. So when I tried to use helm it is trying to install from windows  which is failing. So I cloned from git and changed the nodeselector os to linux for deployment(dashboard and controller)

Everything is up and running but I don't see any recommendations yet. 
As suggested above I checked status which is empty and metrics available is also true.

```
NAME                     SERVICE                      AVAILABLE   AGE 
v1beta1.metrics.k8s.io   kube-system/metrics-server   True        306d
```

I also labeled using cli command

```
kubectl label ns goldilocks goldilocks.fairwinds.com/enabled=true --overwrite=true
kubectl label ns goldilocks goldilocks.fairwinds.com/vpa-update-mode=auto --overwrite=true
```

Then I checked the status of labels as below which is showing as expected

```
kubectl get ns --show-labels
NAME              STATUS   AGE    LABELS
goldilocks        Active   21m    goldilocks.fairwinds.com/enabled=true,goldilocks.fairwinds.com/vpa-update-mode=auto

```

I can't use helm because of above mentioned reason. So how to set installVPA=true via kubectlcli or is labelling same as setting this property? If not what is the approach we should follow to show recommendations.

Please guide me ....!
