### ISSUE TITLE
Error running summary

### ISSUE THREAD

**Issue by srreddy2020** [FairwindsOps/goldilocks#386]
Hi,
I am using goldilocks tool, its installed in K8s.
suddenly its stopped working, In dashboard if i click on any namespace its showing " Error running summary"
All pods are working fine
![image](https://user-images.githubusercontent.com/65938470/142463045-a2be4ca4-3448-4212-a836-132f78f954bd.png)

**Comment by lucasreed** [comment]
👋 Thanks for bringing this to our attention! Can you please let us know what version of goldilocks and version of kubernetes you're using?

**Comment by srreddy2020** [comment]
Hi lucasreed,
I can't find the version details from dashboard, I took the details from deployment files..
containers:
        - name: goldilocks
          image: "quay.io/fairwinds/goldilocks:master"
          imagePullPolicy: Always
          command:
            - /goldilocks
            - dashboard
            - --exclude-containers=linkerd-proxy,istio-proxy
            - -v3

**Comment by lucasreed** [comment]
Ah, pulling the `master` tag of the image is not recommended because as we change requirements (in this case, you are likely missing RBAC changes that are necessary) you will run into situations like this.

Our recommended installation method is by using the helm chart which will have all the necessary RBAC permissions that the newer version needs and also tie your installation to a specific image version (unless it's overridden)

At a minimum I would encourage you to change `:master` to a specific version.

Closing this as there is not an issue with the application.
