### ISSUE TITLE
Various performance issues

### ISSUE THREAD

**Issue by chamburr** [FairwindsOps/goldilocks#536]
There seems to be significant performance issues, some visible effects are slow reconcile times, and loading the dashboard being incredibly slow when there are many resources. I will go into the details on what I think the issues are, and how they could potentially be fixed. Once the issues are addressed, I am expecting a large increase in performance.

One issue is that the underlying function GetAllTopControllers in controller-utils is very slow, because it has to make a lot of API calls. This function is used in two places that can both be avoided. It is used during reconciliation to get the list of controllers, for which we simply fetch a list of well-known controllers (CronJob, DaemonSet, Deployment, Job, StatefulSet) that can be changed through CLI configuration. The function is also used to get the current resource requests and limits for the dashboard, which can be avoided by either referencing the target defined in VPA directly, or again fetching the list of controllers.

Another issue has to do with reconciliation logic. A namespace reconcile currently triggers when the namespace changes or when a pod inside the namespace changes. However, an initial update event is sent for every pod and namespace on controller startup, which means each namespace will be reconciled many many times. On first thought, I am unsure why it is necessary to reconcile on pod change. I thought it would be sufficient for pod create and delete, or better, controller create and delete.

I hope my suggestions can be considered. Thank you!

**Comment by sudermanjr** [comment]
👋🏼  Sorry for the slow response. We have definitely been seeing some of these errors in other places that use controller-utils. Robert just made some fixes to it that should help with performance, so I'm hoping we can get those in and see if it helps. Once that's done, perhaps we can continue this thread to see if there are other opportunities. Thanks!

**Comment by sudermanjr** [comment]
This should have been at least partially addressed by https://github.com/FairwindsOps/goldilocks/pull/557. Please feel free to reopen or open a new issue to address more specific issues.

**Comment by max0ne** [comment]
Is this issue solved? I'm using latest version of Goldilocks, it's using v0.3.2 version of controller-utils. It's still listing all pods when any pod in a namespace is updated.
https://github.com/FairwindsOps/controller-utils/blob/v0.3.2/pkg/controller/controller.go#L136-L155


This generates an n^2 amount of load with n being number of pods in each cluster.

Our cluster used to be using a pretty old version of Goldilocks `v3.2.0` which does not use `controller-utils`, only watches k8s deployment. In my opinion that's the expected behavior, only that it doesn't watch other controllers like StatefulSet and Daemonset, which can be added very easily.
