### ISSUE TITLE
Consider clarify `Error running summary.` error (First time use)

### ISSUE THREAD

**Issue by Dentrax** [FairwindsOps/goldilocks#567]
As a first time user, I just install the latest version using the Helm as documentation recommended as following:

```
$ helm repo add fairwinds-stable https://charts.fairwinds.com/stable
$ kubectl create namespace goldilocks
$ helm install goldilocks --namespace goldilocks fairwinds-stable/goldilocks
```

Add a namespace:
```
kubectl label ns kube-system goldilocks.fairwinds.com/enabled=true
```

Port forward to `8080`:
```
$ kubectl -n goldilocks port-forward svc/goldilocks-dashboard 8080:80
```

Jump a namespace on `http://localhost:8080/dashboard/kube-system` and see the error:
```
Error running summary.
```

Source code: https://github.com/FairwindsOps/goldilocks/blob/db7a6a89f4ba00c221dd403243dfaf55f815787a/pkg/dashboard/dashboard.go#L62-L67

Related issue: https://github.com/FairwindsOps/goldilocks/issues/386

Image: `us-docker.pkg.dev/fairwinds-ops/oss/goldilocks:v4.5.1`

Here is my 5 cents:
* Clarify the error by rephrasing (What should user do?)
* Add the error in the [FAQ](https://goldilocks.docs.fairwinds.com/faq/)?

**Comment by sudermanjr** [comment]
I go back and forth on this. Yes, it would be good to clarify, but there's a chance of exposing more information than you might intend by sending this to the dashboard. Currently, that's why we log the message instead of exposing the details to the dashboard.

Adding to the FAQ is a great idea, and pointing folks to the logs as well.

Perhaps the message could say "Error running summary, please check the dashboard pod logs for details"?
