### ISSUE TITLE
Question: Why use Goldilocks?

### ISSUE THREAD

**Issue by guettli** [FairwindsOps/goldilocks#629]
I prefer the command line to dashboards.

I can run VPA in recommendation-mode without Goldilocks.

What is the benefit of Goldilocks for someone who prefers the terminal to GUIs?

**Comment by sharon-hunters** [comment]
@guettli If you are looking only for recommendation mode for the terminal you should check out this project:
https://github.com/robusta-dev/krr

If you still want to use VPA, Goldilocks actually eases the process since it requires you only to label a namespace, while if are using VPA only, you need to create CR VPA for every single controller (usually K8s Deployment), this can be a tedious task.

**Comment by guettli** [comment]
@sharon-hunters thank you for your hint. The tool krr looks promising.

**Comment by sudermanjr** [comment]
Previous answer hit it on the head. Future releases of Goldilocks will likely be more focused on VPA management rather than just resource recommendations.
